name: Test Checks

on:
  repository_dispatch:
    types:
      - vercel.deployment.ready

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: 'Vercel - Test Checks'
