name: Simple Check

on:
  repository_dispatch:
    types: [vercel.deployment.ready]

env:
  FORCE_PASS: "true"  # Set to "false" to test failure

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "URL: ${{ github.event.client_payload.url }}"
          [ "${{ env.FORCE_PASS }}" = "true" ] && echo "✅ Pass" || (echo "❌ Fail" && exit 1)

      - if: always()
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: "Vercel - Simple Check"