name: Print Vercel Events

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.pending'

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Deployment URL: ${{ github.event.client_payload.url }}"
