name: Test Checks

on:
  repository_dispatch:
    types:
      - vercel.deployment.success

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
